name: "Set up binary cache"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - .github/**
      - assets/**
      - .gitignore

jobs:
  cachix:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package:
          - default
          - nix
          - tidal
          - maximal
    steps:
      - uses: easimon/maximize-build-space@v8
        name: Maximize build space
        with:
          overprovision-lvm: true
          remove-android: true
          remove-dotnet: true
          remove-haskell: true
          remove-codeql: true

      - uses: actions/checkout@v4
        name: Checkout

      - uses: cachix/install-nix-action@v23
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            auto-optimise-store = true
            experimental-features = nix-command flakes
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v12
        with:
          authToken: ${{ secrets.CACHIX_TOKEN }}
          extraPullNames: nix-community
          name: neovim-flake

      - name: Set default git branch (to reduce log spam)
        run: git config --global init.defaultBranch main

      - name: Validate Flakes
        run: nix flake check

      - name: Build neovim-flake with default settings
        run: nix build .#${{ matrix.package }} --print-build-logs
